import Head from "next/head";
//import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.css";
// import styled from "styled-components";
// import { Title, Subtitle } from "@/styles/home";
import { Subtitle } from "@/styles/home";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Subtitle>
          Bienvenido a <a href="https://nextjs.org">Next.js!</a>
        </Subtitle>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <p>Este es mi index.</p>
        <p>
          Ir a{" "}
          <Link href="/hola">
            <a className="">hola</a>
          </Link>{" "}
          con link
        </p>
      </main>
    </div>
  );
}

// const Title = styled.h1`
//   margin: 0;
//   line-height: 1.15;
//   font-size: 4rem;
//   color: #f50554;
//   text-align: center;
// `;
